gitlab-server:
  ports:
    - ":22/tcp"
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${vhost}
  image: gitlab/gitlab-ce:8.5.1-ce.0
  environment:
    - VIRTUAL_HOST=${vhost}
  volumes:
    - /etc/gitlab
    - /var/log/gitlab
    - /var/opt/gitlab

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: tianon/true
  volumes_from:
    - gitlab-server