app:
  image: nexus.docker1.brandung.dev:5000/magento2-php:7-apache
  links:
    - db
    - redis01
    - redis02
    - memcached
  environment:
    - VIRTUAL_HOST=${vhost}
  labels:
    io.rancher.sidekicks: appdata,webdav

appdata:
  image: tianon/true
  volumes_from:
    - app
  labels:
    io.rancher.container.start_once: true

webdav:
  image: visity/webdav
  volumes_from:
    - app
  environment:
    - VIRTUAL_HOST=webdav.${vhost}

dbadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    - VIRTUAL_HOST=phpmyadmin.${vhost}

redis01:
  image: redis

redis02:
  image: redis

memcached:
  image: memcached

db:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=magento
  labels:
    io.rancher.sidekicks: dbdata

dbdata:
  image: tianon/true
  volumes_from:
    - db
  labels:
    io.rancher.container.start_once: true