apache:
  image: magento2
  links:
    - db
  environment:
    - VIRTUAL_HOST=${vhost}
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    - VIRTUAL_HOST=phpmyadmin.${vhost}
db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=${mysql_password}
    - MYSQL_DATABASE=magento