apache:
  image: magento2
  links:
    - db
    - redis-backend-cache
    - redis-page-cache
    - memcached-session
  environment:
    - VIRTUAL_HOST=${vhost}

debian:
  image: debian
  ports:
    - "${ssh_port}:22"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    - VIRTUAL_HOST=phpmyadmin.${vhost}

redis-backend-cache:
  image: redis

redis-page-cache:
  image: redis

memcached-session:
  image: memcached

db:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=magento