apache:
  image: nexus.docker1.brandung.dev:5000/magento2
  links:
    - db
    - redis01
    - redis02
    - memcached
  environment:
    - VIRTUAL_HOST=${vhost}
  volumes:
    - /var/www/html
  labels:
    io.rancher.sidekicks: ssh,apache-data

apache-data:
  image: busybox:1.24
  volumes_from:
    - apache
  command: ["echo", "apache data container"]
  labels:
    io.rancher.container.start_once: true

ssh:
  image: nexus.docker1.brandung.dev:5000/ssh
  volumes_from:
    - apache
  ports:
    - "${ssh_port}:22"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    - VIRTUAL_HOST=phpmyadmin.${vhost}

redis01:
  image: redis

redis02:
  image: redis

memcached:
  image: memcached

db:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=magento
  labels:
    io.rancher.sidekicks: db-data

db-data:
  image: busybox:1.24
  volumes_from:
    - db
  command: ["echo", "db data container"]
  labels:
    io.rancher.container.start_once: true